export type ListingConfig = {
  apiBase: string; // base endpoint e.g. /api/tuition-private-classes
  titleField?: string;
  subtitleField?: string;
  defaultFields?: string[];
  featureKeys?: string[];
};

// Centralized config for known listing types
 export const listingConfigs: Record<string, ListingConfig> = {
  "tuition-private-classes": {
    apiBase: "/api/admin/tuition-private-classes",
    titleField: "title",
    subtitleField: "tutorName",
    defaultFields: [
      "listingType",
      "subjectCategory",
      "teachingMode",
      "classType",
      "tutorQualification",
      "tutorExperienceYears",
      "gradeLevel",
      "minGrade",
      "maxGrade",
      "board",
      "batchSize",
      "feePerMonth",
      "feePerHour",
      "feePerSubject",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "isActive",
      "isFeatured",
      "viewCount",
     
    ],
    featureKeys: [
      "demoClassAvailable",
      "studyMaterialProvided",
      "testSeriesIncluded",
      "doubtClearingSessions",
      "flexibleTimings",
      "weekendClasses",
      "homeTuitionAvailable",
      "onlineClassesAvailable",
    ],
  },
  // Cars & Bikes
  "cars-bikes": {
    apiBase: "/api/admin/cars-bikes",
    titleField: "title",
    subtitleField: "model",
    defaultFields: ["listingType", "vehicleType", "brand", "model", "year", "price", "kilometersDriven", "fuelType", "transmission", "color", "city", "fullAddress", "isActive", "isFeatured", "viewCount"],
  },
  // Second Hand Cars & Bikes
  "second-hand-cars-bikes": {
    apiBase: "/api/admin/second-hand-cars-bikes",
    titleField: "title",
    subtitleField: "model",
    defaultFields: [
      "listingType",
      "vehicleType",
      "brand",
      "model",
      "variant",
      "year",
      "price",
      "kilometersDriven",
      "fuelType",
      "transmission",
      "ownerNumber",
      "registrationNumber",
      "registrationState",
      "registrationYear",
      "insuranceType",
      "insuranceValidUntil",
      "taxValidity",
      "color",
      "bodyType",
      "seatingCapacity",
      "engineCapacity",
      "mileageKmpl",
      "condition",
      "accidentHistory",
      "floodAffected",
      "serviceRecordsAvailable",
      "nocAvailable",
      "isNegotiable",
      "exchangeAccepted",
      "testDriveAvailable",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "isActive",
      "isFeatured",
      "isVerified",
      "viewCount",
     
    ],
  },
  // Fashion & Beauty Products
  "fashion-beauty-products": {
    apiBase: "/api/admin/fashion-beauty-products",
    titleField: "title",
    subtitleField: "productName",
    defaultFields: [
      "listingType",
      "category",
      "subcategory",
      "productType",
      "brand",
      "productName",
      "color",
      "size",
      "material",
      "pattern",
      "style",
      "occasion",
      "gender",
      "ageGroup",
      "fitType",
      "sleeveType",
      "neckType",
      "length",
      "waistSize",
      "inseam",
      "productVolume",
      "skinType",
      "hairType",
      "fragranceType",
      "ingredients",
      "expiryDate",
      "manufacturingDate",
      "shelfLife",
      "price",
      "mrp",
      "discountPercentage",
      "rentalPricePerDay",
      "rentalPricePerWeek",
      "rentalPricePerMonth",
      "minimumRentalPeriod",
      "rentalPeriodUnit",
      "securityDeposit",
      "condition",
      "usageDuration",
      "purchaseDate",
      "ageInMonths",
      "qualityGrade",
      "isOriginal",
      "brandAuthorized",
      "certificateAvailable",
      "authenticationProof",
      "careInstructions",
      "washingInstructions",
      "dryCleanOnly",
      "ironSafe",
      "fabricCare",
      "dermatologicallyTested",
      "crueltyFree",
      "vegan",
      "organic",
      "parabenFree",
      "sulfateFree",
      "allergenInfo",
      "inStock",
      "stockQuantity",
      "sizesAvailable",
      "colorsAvailable",
      "variantOptions",
      "customizationAvailable",
      "customSizing",
      "personalizationOptions",
      "tailoringIncluded",
      "videos",
      "sizeChart",
      "productBrochure",
      "keyFeatures",
      "fabricFeatures",
      "specialFeatures",
      "includedItems",
      "boxContents",
      "isOnSale",
      "saleEndDate",
      "bankOffers",
      "comboOffers",
      "bulkDiscountAvailable",
      "returnPolicy",
      "returnPeriodDays",
      "replacementPolicy",
      "exchangeAvailable",
      "refundAvailable",
      "warrantyAvailable",
      "warrantyPeriod",
      "sellerType",
      "shopName",
      "boutiqueName",
      "designerName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "alternatePhone",
      "whatsappAvailable",
      "whatsappNumber",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "deliveryAvailable",
      "deliveryCharges",
      "freeDelivery",
      "freeDeliveryAbove",
      "sameDayDelivery",
      "expressDelivery",
      "deliveryAreas",
      "shippingOptions",
      "codAvailable",
      "isActive",
      "isFeatured",
      "isVerified",
      "availabilityStatus",
      "viewCount",
     
    ],
  },
  // Car & Bike Rentals
  "car-bike-rentals": {
    apiBase: "/api/admin/car-bike-rentals",
    titleField: "title",
    subtitleField: "brand",
    defaultFields: ["rentalType", "brand", "model", "rentalPricePerDay", "rentalPricePerHour", "minimumRentalDuration", "licenseRequired", "driverAvailable", "city", "fullAddress", "isActive", "isFeatured", "viewCount"],
  },
  // Add other mapping entries as needed. Fallback: infer from type param
};

export const getConfigForType = (type: string) => {
  return listingConfigs[type];
};
