// Shared mapping of subcategory slugs -> API endpoints and display names
export const SUBCATEGORY_API_MAP: Record<string, string> = {
  'TuitionPrivatClasses': '/api/tuition-private-classes',
  'Tuition & Private Classes': '/api/tuition-private-classes',
  'RentalListings': '/api/rental-listings',
  'Rental Listings': '/api/rental-listings',
  'HostelPG': '/api/hostel-listings',
  'Hostel & PG': '/api/hostel-listings',
  'ConstructionMaterials': '/api/construction-materials',
  'Construction Materials': '/api/construction-materials',
  'Construction & Building Materials': '/api/construction-materials',
  'PropertyDeals': '/api/property-deals-public',
  'Property Deals': '/api/property-deals-public',
  'CommercialProperties': '/api/commercial-properties-public',
  'Commercial Properties': '/api/commercial-properties-public',
  'IndustrialLand': '/api/industrial-land-public',
  'Industrial Land': '/api/industrial-land-public',
  'OfficeSpaces': '/api/office-spaces-public',
  'Office Spaces': '/api/office-spaces-public',
  'LocalMarketCommercialProperty': '/api/commercial-properties-public',
  'Local Market Commercial Property': '/api/commercial-properties-public',
  'OfficeSpacesPublic': '/api/office-spaces-public',
  'CompanyOfficeSpace': '/api/office-spaces-public',
  'Company Office Space': '/api/office-spaces-public',
  'IndustrialLandPublic': '/api/industrial-land-public',
  'FactoryIndustrialLand': '/api/industrial-land-public',
  'Factory Industrial Land': '/api/industrial-land-public',
  'Rentals': '/api/rental-listings',
  'Rental - Rooms, Flats, Apartments': '/api/rental-listings',
  'Rental - Rooms, Flats, Apartiments': '/api/rental-listings',
  'HostelPg': '/api/hostel-listings',
  'Hostels & PG': '/api/hostel-listings',
  'CarsBikes': '/api/cars-bikes',
  'Cars & Bikes': '/api/cars-bikes',
  'HeavyEquipment': '/api/heavy-equipment',
  'Heavy Equipment': '/api/heavy-equipment',
  'Heavy Equipment for Sale': '/api/heavy-equipment',
  'Heavy Equipment For Sale': '/api/heavy-equipment',
  'Showrooms': '/api/showrooms',
  'Showrooms (Authorized Second-Hand)': '/api/showrooms',
  'Showrooms (Authorized-Second-hand)': '/api/showrooms',
  'SecondHandCarsBikes': '/api/second-hand-cars-bikes',
  'Second Hand Cars & Bikes': '/api/second-hand-cars-bikes',
  'Second-Hand Cars & Bikes': '/api/second-hand-cars-bikes',
  'CarBikeRentals': '/api/car-bike-rentals',
  'Car & Bike Rentals': '/api/car-bike-rentals',
  'TransportationMovingServices': '/api/transportation-moving-services',
  'Transportation & Moving Services': '/api/transportation-moving-services',
  'VehicleLicenseClasses': '/api/vehicle-license-classes',
  'Vehicle License Classes': '/api/vehicle-license-classes',
  'ElectronicsGadgets': '/api/electronics-gadgets',
  'Electronics & Gadgets': '/api/electronics-gadgets',
  'PhonesTabletsAccessories': '/api/phones-tablets-accessories',
  'Phones, Tablets & Accessories': '/api/phones-tablets-accessories',
  'New Phones & Tablets & Accessories': '/api/phones-tablets-accessories',
  'New Phones & Tablets & Accessories ': '/api/phones-tablets-accessories',
  'SecondHandPhonesTabletsAccessories': '/api/second-hand-phones-tablets-accessories',
  'Second Hand Phones & Accessories': '/api/second-hand-phones-tablets-accessories',
  'Second Hand Phones & Tablets & Accessories': '/api/second-hand-phones-tablets-accessories',
  'Second-Hand Phones & Tablets & Accessories': '/api/second-hand-phones-tablets-accessories',
  'ComputerMobileLaptopRepairServices': '/api/computer-mobile-laptop-repair-services',
  'Computer & Mobile Repair Services': '/api/computer-mobile-laptop-repair-services',
  'Computer, Mobile & Laptop Repair Services': '/api/computer-mobile-laptop-repair-services',
  'CyberCafeInternetServices': '/api/cyber-cafe-internet-services',
  'Cyber Cafe & Internet Services': '/api/cyber-cafe-internet-services',
  'Cyber café & Internet Services': '/api/cyber-cafe-internet-services',
  'Cyber Café / Internet Services': '/api/cyber-cafe-internet-services',
  'TelecommunicationServices': '/api/telecommunication-services',
  'Telecommunication Services': '/api/telecommunication-services',
  'ServiceCentreWarranty': '/api/service-centre-warranty',
  'Service Centre / Warranty': '/api/service-centre-warranty',
  'Service Centre & Warranty': '/api/service-centre-warranty',
  'Service Centre % Warranty': '/api/service-centre-warranty',
  'FurnitureInteriorDecor': '/api/admin/furniture-interior-decor',
  'Furniture & Interior Decor': '/api/admin/furniture-interior-decor',
  'furniture': '/api/admin/furniture-interior-decor',
  'HouseholdServices': '/api/household-services',
  'Household Services': '/api/household-services',
  'EventDecorationServices': '/api/event-decoration-services',
  'Event & Decoration Services': '/api/event-decoration-services',
  'Event & Decoration Services (Marriage Halls, Parties, Café Setup, Decoration Materials)': '/api/event-decoration-services',
  'FashionBeautyProducts': '/api/admin/fashion-beauty-products',
  'Fashion & Beauty Products': '/api/fashion-beauty-products',
  'SareeClothingShopping': '/api/admin/saree-clothing-shopping',
  'Saree & Clothing Shopping': '/api/saree-clothing-shopping',
  'Saree Shopping Clothing': '/api/saree-clothing-shopping',
  'EbooksOnlineCourses': '/api/ebooks-online-courses',
  'E-Books & Online Courses': '/api/ebooks-online-courses',
  'CricketSportsTraining': '/api/cricket-sports-training',
  'Cricket & Sports Training': '/api/cricket-sports-training',
  'PharmacyMedicalStores': '/api/admin/pharmacy-medical-stores',
  'Pharmacy & Medical Stores': '/api/pharmacy-medical-stores',
  'DanceKarateGymYoga': '/api/dance-karate-gym-yoga',
  'Dance, Karate, Gym & Yoga': '/api/dance-karate-gym-yoga',
  'DanceKarateGymYoga Classes': '/api/dance-karate-gym-yoga',
  'LanguageClasses': '/api/language-classes',
  'Language Classes': '/api/language-classes',
  'AcademiesMusicArtsSports': '/api/academy-music-arts',
  'Academies - Music, Arts, Sports': '/api/academy-music-arts',
  'Academies-Music-Arts-Sports': '/api/academy-music-arts',
  'SkillTrainingCertification': '/api/skill-training-certification',
  'Skill Training & Certification': '/api/skill-training-certification',
  'Skill-Training -Certification': '/api/skill-training-certification',
  'SchoolsCollegesCoaching': '/api/schools-colleges-coaching',
  'Schools, Colleges & Coaching': '/api/schools-colleges-coaching',
  'Schools, Colleges, Coaching Institutes': '/api/schools-colleges-coaching',
  'Cricket-Sports Training': '/api/cricket-sports-training',
  'EducationalConsultancyStudyAbroad': '/api/educational-consultancy-study-abroad',
  'Educational Consultancy & Study Abroad': '/api/educational-consultancy-study-abroad',
  'educational-consultancy-study-abroad': '/api/educational-consultancy-study-abroad',
  'JewelryAccessories': '/api/admin/jewelry-accessories',
  'Jewelry & Accessories': '/api/jewelry-accessories',
  'HealthWellnessServices': '/api/admin/health-wellness-services',
  'Health & Wellness Services': '/api/health-wellness-services',
};

export const SUBCATEGORY_NAMES: Record<string, string> = {
  'TuitionPrivatClasses': 'Tuition & Private Classes',
  'RentalListings': 'Rental Listings',
  'HostelPG': 'Hostel & PG',
  'ConstructionMaterials': 'Construction Materials',
  'Construction & Building Materials': 'Construction & Building Materials',
  'PropertyDeals': 'Property Deals',
  'CommercialProperties': 'Commercial Properties',
  'IndustrialLand': 'Industrial Land',
  'OfficeSpaces': 'Office Spaces',
  'CarsBikes': 'Cars & Bikes',
  'HeavyEquipment': 'Heavy Equipment',
  'Showrooms': 'Showrooms',
  'SecondHandCarsBikes': 'Second Hand Cars & Bikes',
  'CarBikeRentals': 'Car & Bike Rentals',
  'TransportationMovingServices': 'Transportation & Moving Services',
  'VehicleLicenseClasses': 'Vehicle License Classes',
  'ElectronicsGadgets': 'Electronics & Gadgets',
  'PhonesTabletsAccessories': 'Phones, Tablets & Accessories',
  'New Phones & Tablets & Accessories': 'New Phones, Tablets & Accessories',
  'SecondHandPhonesTabletsAccessories': 'Second Hand Phones & Accessories',
  'ComputerMobileLaptopRepairServices': 'Computer & Mobile Repair Services',
  'CyberCafeInternetServices': 'Cyber Café / Internet Services',
  'FurnitureInteriorDecor': 'Furniture & Interior Decor',
  'HouseholdServices': 'Household Services',
  'EventDecorationServices': 'Event & Decoration Services',
  'FashionBeautyProducts': 'Fashion & Beauty Products',
  'SareeClothingShopping': 'Saree & Clothing Shopping',
  'EbooksOnlineCourses': 'E-Books & Online Courses',
  'CricketSportsTraining': 'Cricket & Sports Training',
  'PharmacyMedicalStores': 'Pharmacy & Medical Stores',
  'DanceKarateGymYoga': 'Dance, Karate, Gym & Yoga',
  'DanceKarateGymYoga Classes': 'Dance, Karate, Gym & Yoga',
  'LanguageClasses': 'Language Classes',
  'AcademiesMusicArtsSports': 'Academies - Music, Arts, Sports',
  'SkillTrainingCertification': 'Skill Training & Certification',
  'SchoolsCollegesCoaching': 'Schools, Colleges & Coaching',
  'EducationalConsultancyStudyAbroad': 'Educational Consultancy & Study Abroad',
  'JewelryAccessories': 'Jewelry & Accessories',
  'HealthWellnessServices': 'Health & Wellness Services',
  'TelecommunicationServices': 'Telecommunication Services',
  'ServiceCentreWarranty': 'Service Centre & Warranty',
};

export default SUBCATEGORY_API_MAP;
